channels:
- conda-forge
dependencies:
- jupyterlab
- notebook=5.4
- nbconvert=5.3
- ipykernel=4.7
- ipywidgets=7.1
- widgetsnbextension=3.1
- scipy
- matplotlib=2.1
- pandas=0.20
- python=3.6
- jupyterlab_launcher
